# Generated by Django 4.2.3 on 2024-10-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningservice',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='cleaningservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
