# Generated by Django 4.2.3 on 2024-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage', '0003_alter_cleaningservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningservice',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cleaningservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
